#!/usr/bin/env python 

"""
This script will convert TrueRewardsTOU.txt (Terms of Use) and TRUPrivacyPolicy.txt,
which are Google Docs saved to text format, into React components:

    src/components/PrivacyPolicyDoc.js
    src/components/TermsOfUseDoc.js

In case TOU or PP texts change, save the Google Docs to
TrueRewardsTOU.txt and/or TRUPrivacyPolicy.txt in text format,
rerun this script and commit git changes.
"""

import sys

def txt_file_to_html(file_name):
    with open(file_name) as f:
        return txt_to_html(f.readlines())


CENTERED="""TRU Purchaser Portal,Terms of Use,TRU Privacy Policy,Purchaser Portal""".split(',')

H3 = """Theft and Loss
Market Value
Liquidation Risk""".splitlines()

# Last modified:
DATE="Jun 1, 2020"


def clean(line):
    s = line.replace('\xef\xbb\xbf', '').strip().replace("\xe2\x80\x9c",'"').replace("\xe2\x80\x9d", '"').replace('\xe2\x80\x99', "'").replace("\xe2\x80\x94", "&mdash;")
    s = s.replace("www.ADD WEBSITE URL.com", "portal.trusttoken.com")
    s = s.replace("Terms of Use[a]", '<Link to="/terms-of-use"> Terms of Use </Link>')
    s.replace("[a]Add link.", "")
    return s


def is_heading(line):
    return not (line[-1] in '.:/') or line.endswith("U.S.")


def heading(line):
    if '[DATE]' in line:
        return "<p>" + line.replace("[DATE]", DATE) + "</p>"
    if line in CENTERED:
        return '<p style={{textAlign: "center"}}>' + line + '</p>'
    if line in H3:
        return "<h3>" + line + "</h3>"
    return "<h2>" + line + "</h2>"


def txt_to_html(lines):
    in_ul = False
    for line in map(clean, lines):
        if not line or "[a]Add link." in line:
            continue
        if line.startswith('*'):
            if not in_ul:
                yield "<ul>"
                in_ul = True
            yield "<li>" + line[2:] + "</li>"
        else:
            if in_ul:
                yield "</ul>"
                in_ul = False
            if is_heading(line):
                yield(heading(line))
            else:
                yield("<p>" + line + "</p>")


def convert(component_name, text_file, output_file):
    with open(output_file, "w") as f:
        f.write(" // This file is autogenerated. Do not edit! See " + sys.argv[0] + "\n")
        f.write("import React from 'react';\n")
        f.write("import { Link } from 'react-router-dom';\n")
        f.write("const " + component_name + " = props => (\n")
        f.write('<>\n')
        for l in txt_file_to_html(text_file):
            f.write(l + '\n')
        f.write('</>\n')
        f.write(")\n")
        f.write("export default " + component_name + ";\n")


convert("PrivacyPolicyDoc", "TRUPrivacyPolicy.txt", "src/components/PrivacyPolicyDoc.js")
convert("TermsOfUseDoc", "TrueRewardsTOU.txt", "src/components/TermsOfUseDoc.js") 

