FROM node:10 as client

ENV NODE_ENV=development

WORKDIR /app/client

COPY ./client .
COPY ./server ../server

RUN yarn install
RUN yarn build

FROM nginx:1.15.2-alpine
COPY nginx.test.conf /etc/nginx/conf.d/default.conf
COPY --from=client /app/client/build /usr/share/nginx/html
CMD nginx -g 'daemon off;'
EXPOSE 3000
