FROM node:10 as client

ENV NODE_ENV=production

WORKDIR /app/client

COPY ./client .
COPY ./server ../server

RUN yarn install
RUN yarn build

FROM nginx:1.15.2-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=client /app/client/build /usr/share/nginx/html
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
EXPOSE $PORT
