 // This file is autogenerated. Do not edit! See ./convert_legal_to_react.py
import React from 'react';
import { Link } from 'react-router-dom';
const PrivacyPolicyDoc = props => (
<>
<h1 style={{textAlign: "center"}}>TRU Privacy Policy</h1>
<h1 style={{textAlign: "center"}}>Purchaser Portal</h1>
<h2>Introduction</h2>
<p>TrustToken, Inc. ("Company," "our," "we") understands the importance of privacy, especially when it comes to your personal information. Data privacy and your trust are our top priorities, and in this Privacy Policy we explain what information we collect from you when you use our online TRU purchaser portal (the "Portal"), how we will use this information, and the very limited ways that we may share your information. Please read this policy carefully to understand our policies and practices regarding your information, as you agree to this Privacy Policy by using the Portal. If you do not agree with our policies and practices, do not use the Portal. This Privacy Policy is part of our <Link to="/terms-of-use"> Terms of Use </Link>.</p>
<h2>Users Under Age 18</h2>
<p>The Portal is only intended for adults eighteen (18) years of age and older. You are not allowed to use the Portal or provide information on it if you are under eighteen (18) years of age. If we learn we have received personal information from or about a child under 13 without verification of parental consent, we will delete that information immediately. If you believe we might have any information from or about a child under thirteen (13) without parental consent, please contact us immediately at <a href="mailto:legal@trusttoken.com">legal@trusttoken.com</a>.</p>
<h2>What Data Do We Collect?</h2>
<p>We collect several types of information from and about users of the Portal depending on how they are using the Portal, including:</p>
<ul>
<li>Personal identification information about you, such as your name, address, phone number, and email address;</li>
<li>Information about the cryptocurrency wallet addresses you provide; and</li>
<li>Any other information you voluntarily provide on the Portal in the ordinary course of the continuation of the relationship;</li>
<li>Information about your internet connection, the equipment you use to access the Portal, and Portal usage details; and</li>
<li>We may log information using "cookies." Cookies are small data files stored on your hard drive by a website. We may use both session Cookies (which expire once you close your web browser) and persistent Cookies (which stay on your computer until you delete them) to provide you with a more personal and interactive experience on our Portal. This type of information is collected to make the Portal more useful to you and to tailor the experience with us to meet your special interests and needs.</li>
</ul>
<h2>How Do We Collect Your Data?</h2>
<p>You directly provide us with most of the data we collect. We collect data and process data when you:</p>
<ul>
<li>Register online for an account or enter information into the Portal when prompted or permitted.</li>
<li>Voluntarily complete a customer survey or provide feedback on any of our message boards or via email.</li>
<li>Use or view our Portal via your browser’s cookies.</li>
<li>Navigate through the Portal. We collect generic information about your usage and equipment automatically, such as usage details, IP addresses, web browser preferences, and information collected through cookies and other tracking technologies.</li>
<li>Direct the Company to deliver digital assets to a specified cryptocurrency wallet address.</li>
</ul>
<p>Although we do not correlate tracking information to individuals, some information collected, such as IP addresses, will be unique.</p>
<h2>Do Not Track Settings</h2>
<p>We do not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.</p>
<h2>How Will We Use Your Data?</h2>
<p>From time to time, it is necessary for customers to supply us with data in connection with the opening or continuation of accounts, the establishment or continuation of facilities or provision of services, or in compliance with any laws or guidelines issued by regulatory or other authorities. We use the information that we collect about you or that you provide to us, including personal information:</p>
<ul>
<li>To email you with special offers on other products and services we think you might like.</li>
<li>To continue the daily operation of the services and facilities provided to customers.</li>
<li>To meet the requirements to make disclosures under the requirements of any law binding on the Portal under and for the purposes of any guidelines issued by regulatory or other authorities with which the Portal is expected to comply.</li>
<li>To protect, investigate, and deter against fraudulent, unauthorized, or illegal activity.</li>
<li>To provide you with customer service, information, products, or services that you request from us.</li>
<li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection.</li>
<li>To notify you about changes to the Portal or any products or services we offer or provide though it.</li>
<li>In any other way we may describe when you provide the information</li>
</ul>
<h2>Disclosure of Your Information</h2>
<p>If you agree, we will share your data with our affiliate companies so that they may offer you their products and services. These affiliate companies include, but are not limited to, TrueCoin, LLC. We only collect personal information that we believe to be relevant and required to conduct our business. We may share your personal information with our business partners and service providers, but only to the extent that they each need to know specific information to continue to provide the Portal or services to you. This includes:</p>
<ul>
<li>Our contractors, employees, service providers, and other third parties that we use to support our business and improve the Portal;</li>
<li>To a buyer or other successor in the event of a merger or reorganization if the personal information of our users is part of the assets transferred;</li>
<li>To fulfill the purpose for which you provide it;</li>
<li>To comply with any court order, law, or legal process, including to respond to any government or regulatory request;</li>
<li>To third party contractors in order to analyze Portal performance and user behavior and/or to improve the Portal;</li>
<li>If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Portal, our users, or others; or</li>
<li>For any other purpose disclosed by us when you provide the information. We may disclose aggregated information about our users, which means information that does not identify any individual, without restriction. As an example, we may include in our marketing materials that a certain percentage of our users are female, but we won’t share a list of all female users in these materials.</li>
</ul>
<h2>How Do We Store Your Data?</h2>
<p>To provide you with the Services described in our Terms of Use, we may securely store, process and transmit information in the United States and locations around the world - including those outside your country. In order to comply with local laws and regulations, we will keep your personal identifying information for seven (7) years from the date you terminate your account. Once this time period has expired, we will delete your data by deleting it from our Postgres relational database and scrubbing it from all third-party systems.</p>
<h2>Data Security</h2>
<p>We have implemented measures designed to secure your personal information from accidental loss and from unauthorized access. For example, access by a user to his or her personal information is available through a unique customer ID and password selected by the user that should be regularly updated. This information is encrypted through the Portal with Secure Socket Layer technology (SSL) and is also encrypted when it is stored by us to prevent unauthorized parties from viewing such information. Also, we perform regular malware monitoring of the Portal and all servers and computers used by us to support the Portal. All Company employees are required to adhere to our security and confidentiality procedures and undergo training related to maintaining the security of user personal information. The safety and security of your information also depends on you. Where you have chosen a password for access to certain parts of the Portal, you are responsible for keeping this password confidential. We ask you not to share your password with anyone and be careful about giving out information to other users on the Portal if requested. Unfortunately, the transmission of information via the internet is not completely secure. Although we do our best to protect your personal information, we cannot guarantee the security of your personal information transmitted to the Portal. Any transmission of personal information is at your own risk. We are not responsible for circumvention of any privacy settings or security measures contained on the Portal.</p>
<h2>Marketing</h2>
<p>We would like to send you information about our products and services of ours that we think you may like, as well as those of our partner companies, including Cred and Nexo. If you have agreed to receive marketing, you may always opt out at a later date. You have the right at any time to stop us from contacting you for marketing purposes or giving your data to other members of our affiliate group. If you no longer wish to be contacted for marketing purposes, please unsubscribe from the marketing emails via the ‘unsubscribe’ link provided in the footer of the most recent marketing email or email support@trusttoken.com and request to be removed from all marketing emails.</p>
<h2>What Are Your Data Protection Rights?</h2>
<p>Our Company would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following: The right to access - You have the right to request us for copies of your personal data. We may charge you a small fee for this service. The right to rectification - You have the right to request that we correct any information you believe is inaccurate. You also have the right to request us to complete the information you believe is incomplete. The right to erasure - You have the right to request that we erase your personal data, under certain conditions, and in compliance with applicable laws and regulations. The right to restrict processing - You have the right to request that we restrict the processing of your personal data, under certain conditions, and in compliance with applicable laws and regulations. The right to object to processing - You have the right to object to our processing of your personal data, under certain conditions, and in compliance with applicable laws and regulations. The right to data portability - You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions, and in compliance with applicable laws and regulations. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us at: legal@truecoin.com.</p>
<h2>Accessing and Correcting Your Information</h2>
<p>You can review and change your personal information by logging into the Portal and visiting your account page. You may also send us an email at customerservice@truecoin.com to request access to, correct, or delete any personal information that you have provided to us. We may not accommodate a request to change information if we believe the change would violate any law or legal requirement or cause the information to be incorrect.</p>
<h2>What Are Cookies?</h2>
<p>Cookies are text files placed on your computer to collect standard Internet log information and visitor behavior information. When you visit our websites, we may collect information from you automatically through cookies or similar technology. For further information, visit allaboutcookies.org.</p>
<h2>How Do We Use Cookies?</h2>
<p>We uses cookies in a range of ways to improve your experience on our website, including:</p>
<ul>
<li>Keeping you signed in</li>
<li>Understanding how you use our website</li>
</ul>
<h2>What Types of Cookies Do We Use?</h2>
<p>There are a number of different types of cookies, however, our website uses:</p>
<ul>
<li>Functionality - Our Company uses these cookies so that we recognize you on our website and remember your previously selected preferences. These could include what language you prefer and location you are in. A mix of first-party and third-party cookies are used.</li>
<li>Advertising - Our Company uses these cookies to collect information about your visit to our website, the content you viewed, the links you followed and information about your browser, device, and your IP address. Our Company sometimes shares some limited aspects of this data with third parties for advertising purposes. We may also share online data collected through cookies with our advertising partners. This means that when you visit another website, you may be shown advertising based on your browsing patterns on our website.</li>
</ul>
<h2>How To Manage Your Cookies</h2>
<p>You can set your browser not to accept cookies, and the above website tells you how to remove cookies from your browser. However, in a few cases, some of our website features may not function as a result.</p>
<h2>Third Party Links</h2>
<p>The Portal may contain links that lead to other websites, and the Company is not responsible for the privacy practices, content, and/or activities of these linked websites. Nonetheless, we seek to protect the integrity of the Portal and welcome any feedback about these external websites.</p>
<h2>Privacy Policies From Other Websites</h2>
<p>Our websites contain links to other websites. Our privacy policy applies only to our websites, so if you click on a link to another website, you should read their privacy policy.</p>
<h2>Changes to Our Privacy Policy</h2>
<p>We may change this privacy policy at anytime. If we make any changes, we will change the Last Updated date above.</p>
<h2>Contact Information</h2>
<p>To ask questions, comment about this Privacy Policy and our privacy practices, or you would like to exercise one of your data protection rights, please do not hesitate to contact us. contact us at <a href="mailto:legal@trusttoken.com">legal@trusttoken.com</a>.</p>
<h2>How To Contact The Appropriate Authorities</h2>
<p>Should you wish to report a complaint or if you feel that we have not addressed your concern in a satisfactory manner, you may contact the Information Commissioner’s Office: https://ico.org.uk/global/contact-us/</p>
</>
)
export default PrivacyPolicyDoc;
